name = "OpenBLAS32"
uuid = "51095b67-9e93-468d-a683-508b52f74e81"
authors = ["Viral B. Shah <ViralBShah@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
